// src/lib/components/AddTransactionModal.svelte
<script lang="ts">
  import { X, Plus, User, FileText, Calendar, Tag, ChevronDown } from 'lucide-svelte';
  import type { Category } from '../../types';

  export let isOpen = false;
  export let variant: 'default' | 'header' | 'fab' = 'default';
  export let categories: Category[];
  export let onSave: (data: any) => void;
  export let onClose: () => void;

  let type: 'income' | 'expense' = 'expense';
  let amount: number | null = null;
  let category_id: number | null = null;
  let date = new Date().toISOString().split('T')[0];
  let person_name = '';
  let description = '';

  $: filteredCategories = categories.filter(c => c.type === type);

  function resetForm() {
    type = 'expense';
    amount = null;
    category_id = null;
    date = new Date().toISOString().split('T')[0];
    person_name = '';
    description = '';
  }

  function handleSave() {
    if (amount && category_id && date) {
      onSave({ type, amount, category_id, date, person_name, description });
      resetForm();
      onClose();
    }
  }

  function handleBackdropClick(e: MouseEvent) {
    if (e.target === e.currentTarget) onClose();
  }
</script>

{#if isOpen}
  <!-- svelte-ignore a11y-click-events-have-key-events -->
  <!-- svelte-ignore a11y-no-static-element-interactions -->
  <div class="modal-backdrop" on:click={handleBackdropClick}>
    <div class="modal-content glass-card animate-modal">
      <div class="modal-header">
        <h2 style="font-size: 1.25rem; margin: 0;">Tambah Transaksi</h2>
        <button class="btn-icon" on:click={onClose}>
          <X size={20} />
        </button>
      </div>

      <div class="form-container">
        <!-- Type Switcher -->
        <div class="type-switcher">
          <button 
            class="type-btn {type === 'expense' ? 'active expense' : ''}" 
            on:click={() => type = 'expense'}
          >
            Pengeluaran
          </button>
          <button 
            class="type-btn {type === 'income' ? 'active income' : ''}" 
            on:click={() => type = 'income'}
          >
            Pemasukan
          </button>
        </div>

        <div class="form-grid">
          <!-- Amount -->
          <div class="form-group full">
            <label for="amount">Jumlah (IDR)</label>
            <div class="input-wrapper">
              <span class="currency-prefix">Rp</span>
              <input 
                type="number" 
                id="amount"
                placeholder="0" 
                style="padding-left: 2.8rem; font-size: 1.25rem; font-weight: 700;" 
                bind:value={amount}
              />
            </div>
          </div>

          <!-- Category -->
          <div class="form-group half">
            <label for="category">Kategori</label>
            <div class="input-wrapper">
              <select id="category" bind:value={category_id}>
                <option value={null}>Pilih Kategori</option>
                {#each filteredCategories as cat}
                  <option value={cat.id}>{cat.name}</option>
                {/each}
              </select>
              <Tag size={16} class="input-icon-left" />
              <ChevronDown size={16} class="input-icon-right" />
            </div>
          </div>

          <!-- Date -->
          <div class="form-group half">
            <label for="date">Tanggal</label>
            <div class="input-wrapper">
              <input type="date" id="date" bind:value={date} />
              <Calendar size={16} class="input-icon-left" />
            </div>
          </div>

          <!-- Conditional Person Name -->
          {#if category_id === 12}
            <div class="form-group full animate-slide">
              <label for="person">Nama Orang (Pemberi/Penerima Utang)</label>
              <div class="input-wrapper">
                <input 
                  type="text" 
                  id="person"
                  placeholder="Masukkan nama..." 
                  bind:value={person_name}
                />
                <User size={16} class="input-icon-left" />
              </div>
            </div>
          {/if}

          <!-- Description -->
          <div class="form-group full">
            <label for="desc">Keterangan</label>
            <div class="input-wrapper">
              <textarea 
                id="desc"
                placeholder="Catatan tambahan..." 
                style="height: 60px; resize: none;"
                bind:value={description}
              ></textarea>
              <FileText size={16} class="input-icon-left" style="top: 1rem; transform: none;" />
            </div>
          </div>
        </div>

        <button 
          class="btn-primary" 
          style="width: 100%; padding: 0.9rem; margin-top: 1rem; font-weight: 600;"
          disabled={!amount || !category_id}
          on:click={handleSave}
        >
          Simpan Transaksi
        </button>
      </div>
    </div>
  </div>
{/if}

{#if variant === 'header'}
  <button class="btn-primary" on:click={() => isOpen = true}>
    <Plus size={18} /> Transaksi
  </button>
{:else if variant === 'fab'}
  <button class="fab-btn" on:click={() => isOpen = true} title="Tambah Transaksi">
    <Plus size={28} />
  </button>
{/if}

<style>
  .modal-backdrop {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.6);
    backdrop-filter: blur(4px);
    z-index: 1000;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 1rem;
  }
  .modal-content {
    width: 100%;
    max-width: 480px;
    max-height: 95vh;
    padding: 1.5rem;
    overflow-y: auto;
    position: relative;
  }
  .animate-modal {
    animation: modalFadeIn 0.3s ease-out;
  }
  @keyframes modalFadeIn {
    from { opacity: 0; transform: scale(0.95) translateY(10px); }
    to { opacity: 1; transform: scale(1) translateY(0); }
  }
  .modal-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 1.5rem;
  }
  .form-container {
    display: flex;
    flex-direction: column;
    gap: 1.25rem;
  }
  .type-switcher {
    display: flex;
    background: rgba(255, 255, 255, 0.05);
    padding: 4px;
    border-radius: 12px;
    gap: 4px;
  }
  .type-btn {
    flex: 1;
    padding: 0.6rem;
    border: none;
    background: none;
    color: var(--text-secondary);
    border-radius: 8px;
    cursor: pointer;
    font-size: 0.9rem;
    font-weight: 600;
    transition: all 0.2s;
  }
  .type-btn.active.expense { background: var(--expense); color: white; }
  .type-btn.active.income { background: var(--income); color: white; }
  
  .form-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1rem;
  }
  .form-group.full { grid-column: span 2; }
  .form-group label {
    display: block;
    font-size: 0.75rem;
    font-weight: 600;
    color: var(--text-secondary);
    margin-bottom: 0.4rem;
    text-transform: uppercase;
  }
  .input-wrapper {
    position: relative;
  }
  .currency-prefix {
    position: absolute;
    left: 1rem;
    top: 50%;
    transform: translateY(-50%);
    font-weight: 700;
    color: var(--text-secondary);
  }
  :global(.input-icon-left) {
    position: absolute;
    left: 1rem;
    top: 50%;
    transform: translateY(-50%);
    color: var(--text-secondary);
  }
  :global(.input-icon-right) {
    position: absolute;
    right: 1rem;
    top: 50%;
    transform: translateY(-50%);
    color: var(--text-secondary);
    pointer-events: none;
  }
  select, input, textarea {
    padding-left: 2.8rem;
  }
  .btn-icon {
    background: rgba(255, 255, 255, 0.05);
    border: none;
    color: white;
    padding: 0.4rem;
    border-radius: 8px;
    cursor: pointer;
  }
  .fab-btn {
    position: fixed;
    bottom: 2rem;
    right: 2rem;
    width: 60px;
    height: 60px;
    border-radius: 50%;
    background: var(--primary);
    color: white;
    border: none;
    box-shadow: 0 4px 20px rgba(59, 130, 246, 0.5);
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.2s;
    z-index: 100;
  }
  .fab-btn:hover {
    transform: scale(1.1) rotate(90deg);
  }
  .animate-slide {
    animation: slideDown 0.3s ease-out;
  }
  @keyframes slideDown {
    from { opacity: 0; transform: translateY(-10px); }
    to { opacity: 1; transform: translateY(0); }
  }
</style>

// src/components/AddTransactionModal.tsx
'use client';

import { useState, useTransition } from 'react';
import { Category } from '@/lib/types';
import { addTransaction } from '@/lib/actions';
import { Plus } from 'lucide-react';

export default function AddTransactionModal({ 
  categories, 
  variant = 'default' 
}: { 
  categories: Category[], 
  variant?: 'default' | 'header' | 'fab' 
}) {
  const [isOpen, setIsOpen] = useState(false);
  const [type, setType] = useState<'income' | 'expense'>('expense');
  const [isPending, startTransition] = useTransition();

  const [formData, setFormData] = useState({
    amount: '',
    category_id: '',
    description: '',
    person_name: '',
    date: new Date().toISOString().split('T')[0],
  });

  const selectedCategory = categories.find(c => c.id === parseInt(formData.category_id));
  const isLoanCategory = selectedCategory?.name.toLowerCase().includes('utang ke orang');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    startTransition(async () => {
      await addTransaction({
        type,
        amount: parseFloat(formData.amount),
        category_id: parseInt(formData.category_id),
        description: formData.description,
        person_name: isLoanCategory ? formData.person_name : undefined,
        date: formData.date,
      });
      setIsOpen(false);
      setFormData({
        amount: '',
        category_id: '',
        description: '',
        person_name: '',
        date: new Date().toISOString().split('T')[0],
      });
    });
  };

  if (!isOpen) {
    if (variant === 'header') return (
      <button className="btn-primary" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', whiteSpace: 'nowrap', padding: '0.6rem 0.8rem' }} onClick={() => setIsOpen(true)}>
        <Plus size={18} /> <span className="hide-mobile">Transaksi</span>
      </button>
    );

    if (variant === 'fab') return (
      <button 
        onClick={() => setIsOpen(true)}
        style={{ 
          width: '60px', 
          height: '60px', 
          borderRadius: '50%', 
          background: 'var(--primary)', 
          color: '#fff', 
          border: 'none', 
          cursor: 'pointer', 
          boxShadow: '0 10px 25px var(--primary-glow)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          transition: 'transform 0.2s'
        }}
        onMouseOver={e => e.currentTarget.style.transform = 'scale(1.1)'}
        onMouseOut={e => e.currentTarget.style.transform = 'scale(1)'}
      >
        <Plus size={32} />
      </button>
    );

    return (
      <div className="glass-card" style={{ 
        display: 'flex', 
        flexDirection: 'column', 
        justifyContent: 'center', 
        alignItems: 'center', 
        gap: '1rem', 
        background: 'linear-gradient(135deg, rgba(255, 255, 255, 0.05) 0%, rgba(255, 255, 255, 0) 100%)',
        borderStyle: 'dashed',
        borderColor: 'var(--card-border)'
      }}>
        <div style={{ background: 'var(--primary)', padding: '0.75rem', borderRadius: '50%' }}>
          <Plus size={24} color="white" />
        </div>
        <div style={{ textAlign: 'center' }}>
          <h3 style={{ marginBottom: '0.25rem' }}>Catat Transaksi</h3>
          <p className="text-muted">Tambah pendapatan atau pengeluaran baru</p>
        </div>
        <button className="btn-primary" style={{ width: '100%', marginTop: '0.5rem' }} onClick={() => setIsOpen(true)}>
          Buka Formulir
        </button>
      </div>
    );
  }

  return (
    <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.85)', backdropFilter: 'blur(8px)', zIndex: 100, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '1rem' }}>
      <div className="glass-card" style={{ 
        width: '100%', 
        maxWidth: '480px', 
        padding: '1.5rem 1.75rem', 
        boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
        maxHeight: '95vh',
        overflowY: 'auto',
        animation: 'modalFadeIn 0.3s ease'
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.25rem' }}>
          <h2 style={{ fontSize: '1.25rem' }}>Tambah Transaksi</h2>
          <button onClick={() => setIsOpen(false)} style={{ background: 'none', border: 'none', color: 'var(--muted)', cursor: 'pointer', padding: '0.25rem' }}>
            <Plus size={24} style={{ transform: 'rotate(45deg)' }} />
          </button>
        </div>
        <div style={{ display: 'flex', gap: '0.75rem', marginBottom: '1.5rem', padding: '0.2rem', background: 'var(--glass)', borderRadius: '10px' }}>
          <button 
            type="button"
            onClick={() => setType('expense')}
            style={{ 
              flex: 1, 
              padding: '0.6rem', 
              borderRadius: '8px', 
              border: 'none', 
              background: type === 'expense' ? 'var(--expense)' : 'transparent', 
              color: '#fff', 
              cursor: 'pointer',
              fontWeight: 600,
              transition: 'all 0.2s',
              fontSize: '0.9rem'
            }}
          >
            Pengeluaran
          </button>
          <button 
            type="button"
            onClick={() => setType('income')}
            style={{ 
              flex: 1, 
              padding: '0.6rem', 
              borderRadius: '8px', 
              border: 'none', 
              background: type === 'income' ? 'var(--income)' : 'transparent', 
              color: '#fff', 
              cursor: 'pointer',
              fontWeight: 600,
              transition: 'all 0.2s',
              fontSize: '0.9rem'
            }}
          >
            Pendapatan
          </button>
        </div>

        <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '0.85rem' }}>
          <div>
            <label className="text-muted" style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.8rem' }}>Tanggal</label>
            <input 
              type="date" 
              required
              value={formData.date}
              onChange={e => setFormData({...formData, date: e.target.value})}
            />
          </div>

          <div>
            <label className="text-muted" style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.8rem' }}>Kategori</label>
            <select 
              required
              value={formData.category_id}
              onChange={e => setFormData({...formData, category_id: e.target.value})}
            >
              <option value="">Pilih Kategori</option>
              {categories.filter(c => c.type === type).map(c => (
                <option key={c.id} value={c.id}>{c.name}</option>
              ))}
            </select>
          </div>

          {isLoanCategory && (
            <div style={{ animation: 'modalFadeIn 0.3s ease' }}>
              <label className="text-muted" style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.8rem' }}>Nama Orang</label>
              <input 
                type="text" 
                placeholder="Siapa yang diberi utang?"
                required
                value={formData.person_name}
                onChange={e => setFormData({...formData, person_name: e.target.value})}
              />
            </div>
          )}

          <div>
            <label className="text-muted" style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.8rem' }}>Jumlah (IDR)</label>
            <input 
              type="number" 
              placeholder="0"
              required
              value={formData.amount}
              onChange={e => setFormData({...formData, amount: e.target.value})}
            />
          </div>

          <div>
            <label className="text-muted" style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.8rem' }}>Keterangan</label>
            <textarea 
              placeholder="Catatan tambahan..."
              value={formData.description}
              onChange={e => setFormData({...formData, description: e.target.value})}
              style={{ minHeight: '60px' }} 
            />
          </div>

          <div style={{ display: 'flex', gap: '1rem', marginTop: '0.5rem' }}>
            <button type="button" onClick={() => setIsOpen(false)} style={{ flex: 1, padding: '0.75rem', borderRadius: '10px', border: '1px solid var(--card-border)', background: 'transparent', color: '#fff', cursor: 'pointer', fontSize: '0.9rem' }}>
              Batal
            </button>
            <button type="submit" disabled={isPending} className="btn-primary" style={{ flex: 1, fontSize: '0.9rem' }}>
              {isPending ? 'Menyimpan...' : 'Simpan Transaksi'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
