// src/components/TransactionFilters.tsx
'use client';

import { useRouter, useSearchParams } from 'next/navigation';
import { Category } from '@/lib/types';
import { Search, Calendar, Tag } from 'lucide-react';
import { useState, useEffect } from 'react';

export default function TransactionFilters({ categories }: { categories: Category[] }) {
  const router = useRouter();
  const searchParams = useSearchParams();

  const [filters, setFilters] = useState({
    start: searchParams.get('start') || '',
    end: searchParams.get('end') || '',
    cat: searchParams.get('cat') || '',
    person: searchParams.get('person') || '',
  });

  const updateFilters = () => {
    const params = new URLSearchParams();
    if (filters.start) params.set('start', filters.start);
    if (filters.end) params.set('end', filters.end);
    if (filters.cat) params.set('cat', filters.cat);
    if (filters.person) params.set('person', filters.person);
    
    router.push(`?${params.toString()}`);
  };

  return (
    <div className="glass-card" style={{ marginBottom: '1.5rem', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: '1rem', padding: '1rem' }}>
      <div>
        <label className="text-muted" style={{ fontSize: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.25rem', marginBottom: '0.25rem' }}>
          <Calendar size={12} /> Dari
        </label>
        <input 
          type="date" 
          value={filters.start}
          onChange={e => setFilters({...filters, start: e.target.value})}
          onBlur={updateFilters}
        />
      </div>
      <div>
        <label className="text-muted" style={{ fontSize: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.25rem', marginBottom: '0.25rem' }}>
          <Calendar size={12} /> Sampai
        </label>
        <input 
          type="date" 
          value={filters.end}
          onChange={e => setFilters({...filters, end: e.target.value})}
          onBlur={updateFilters}
        />
      </div>
      <div>
        <label className="text-muted" style={{ fontSize: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.25rem', marginBottom: '0.25rem' }}>
          <Tag size={12} /> Kategori
        </label>
        <select 
          value={filters.cat}
          onChange={e => {
            const val = e.target.value;
            setFilters({...filters, cat: val});
            // Manual trigger for select
            const params = new URLSearchParams(window.location.search);
            if (val) params.set('cat', val); else params.delete('cat');
            router.push(`?${params.toString()}`);
          }}
        >
          <option value="">Semua</option>
          {categories.map(c => (
            <option key={c.id} value={c.id}>{c.name}</option>
          ))}
        </select>
      </div>
      <div>
        <label className="text-muted" style={{ fontSize: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.25rem', marginBottom: '0.25rem' }}>
          <Search size={12} /> Nama Orang
        </label>
        <input 
          type="text" 
          placeholder="Cari nama..."
          value={filters.person}
          onChange={e => setFilters({...filters, person: e.target.value})}
          onKeyDown={e => e.key === 'Enter' && updateFilters()}
          onBlur={updateFilters}
        />
      </div>
    </div>
  );
}

// src/lib/components/TransactionFilters.svelte
<script lang="ts">
  import { Search, Filter, X } from 'lucide-svelte';
  import type { Category } from '../../types';

  export let categories: Category[];
  export let filters: {
    startDate?: string;
    endDate?: string;
    categoryId?: number;
    personName?: string;
  };
  export let onFilterChange: () => void;
</script>

<div class="glass-card" style="margin-bottom: 2rem; padding: 1.25rem;">
  <div style="display: flex; align-items: center; gap: 0.5rem; margin-bottom: 1.25rem;">
    <Filter size={18} class="text-muted" />
    <h3 style="font-size: 1rem; margin: 0;">Filter & Pencarian</h3>
  </div>

  <div class="filter-grid">
    <div class="filter-group">
      <label for="search_name">Nama Orang</label>
      <div style="position: relative;">
        <input 
          type="text" 
          id="search_name"
          placeholder="Cari nama..." 
          bind:value={filters.personName}
          on:change={onFilterChange}
        />
        <Search size={16} class="input-icon" />
      </div>
    </div>

    <div class="filter-group">
      <label for="filter_category">Kategori</label>
      <select 
        id="filter_category"
        bind:value={filters.categoryId}
        on:change={onFilterChange}
      >
        <option value={undefined}>Semua Kategori</option>
        {#each categories as cat}
          <option value={cat.id}>{cat.name}</option>
        {/each}
      </select>
    </div>

    <div class="filter-group">
      <label for="start_date">Dari Tanggal</label>
      <input 
        type="date" 
        id="start_date"
        bind:value={filters.startDate}
        on:change={onFilterChange}
      />
    </div>

    <div class="filter-group">
      <label for="end_date">Sampai Tanggal</label>
      <input 
        type="date" 
        id="end_date"
        bind:value={filters.endDate}
        on:change={onFilterChange}
      />
    </div>
  </div>

  {#if filters.startDate || filters.endDate || filters.categoryId || filters.personName}
    <div style="margin-top: 1.25rem; display: flex; justify-content: flex-end;">
      <button 
        class="btn-text" 
        style="display: flex; align-items: center; gap: 0.4rem; font-size: 0.8rem;"
        on:click={() => {
          filters = { startDate: undefined, endDate: undefined, categoryId: undefined, personName: undefined };
          onFilterChange();
        }}
      >
        <X size={14} /> Bersihkan Filter
      </button>
    </div>
  {/if}
</div>

<style>
  .filter-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 1.25rem;
  }
  .filter-group {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }
  .filter-group label {
    font-size: 0.75rem;
    font-weight: 600;
    color: var(--text-secondary);
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }
  :global(.input-icon) {
    position: absolute;
    right: 0.8rem;
    top: 50%;
    transform: translateY(-50%);
    color: var(--text-secondary);
    pointer-events: none;
  }
  .btn-text {
    background: none;
    border: none;
    color: var(--expense);
    cursor: pointer;
    opacity: 0.8;
    transition: opacity 0.2s;
  }
  .btn-text:hover {
    opacity: 1;
    text-decoration: underline;
  }
</style>
